# Cấu hình màn hình OLED
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# Cấu hình quản lý năng lượng
CONFIG_ZMK_IDLE_TIMEOUT=150000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Cấu hình đánh thức
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_USB=y

# Cải thiện ổn định kết nối BLE
CONFIG_BT_BUF_ACL_RX_SIZE=512
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251

CONFIG_ZMK_POINTING=y
#CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
